# theme.toml for Hugo-MDL
# See http://jatkinson.me for an example

name = "Hugo-MDL"
license = "Apache 2.0"
licenselink = "https://github.com/jchatkinson/hugo-materialized/blob/master/LICENSE.md"
description = "a simple theme to show your bio, blog, and projects - based on Google's Material Design Lite library"
homepage = "https://github.com/jchatkinson/Hugo-MDL/"
tags = ["blog", "projects","portfolio","Material Design Lite","MDL","Material Design"]
features = ["blog", "project showcase", "portfolio", "profile","responsive","Material Design"]
min_version = 0.13

[author]
  name = "Jeremy Atkinson"
  homepage = "jatkinson.me"
  email = "jeremy@jatkinson.me"